version: '3.8'

services:
  backend:
    build: ./backend
    container_name: wind-analysis-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    volumes:
      - ./backend/temp:/app/temp
      - ~/.cdsapirc:/root/.cdsapirc:ro
    restart: unless-stopped
    networks:
      - wind-analysis-network

  frontend:
    build: ./frontend
    container_name: wind-analysis-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - wind-analysis-network

networks:
  wind-analysis-network:
    driver: bridge

volumes:
  backend_temp:
    driver: local

